Merge branch '171-melhorias-na-instalacao-e-build' into 'staging'

diff --git a/environment/bin/build b/environment/bin/build
--- a/environment/bin/build
+++ b/environment/bin/build
@@ -147,6 +147,153 @@ is_dist_build() {
 	[[ "${_arg_target}" == "dist" ]]
 }
 
+main() {
+	parse_commandline "$@"
+	handle_passed_args_count
+	assign_positional_args 1 "${_positionals[@]}"
+	import_shell_helpers
+
+	# Load project environment variables
+	# Deactivate debug for this action because it generate a lot of output
+	set +x
+	if ! dotenv_exists; then
+		echo ".env does not exist. A copy has been created."
+		cp .env.example .env
+	fi
+
+	dotenv .env
+
+	set -x
+
+	pull_fresh_images
+	if is_dev_build && is_filesystem_build; then
+		pull_test_fresh_images
+		enable_pre_commit
+	fi
+
+	set_script_variables
+
+	if is_filesystem_build; then
+		create_directory_and_give_permissions_to_http_user ${UPLOADS_DIR}
+		create_directory_and_give_permissions_to_http_user ${UPGRADE_DIR}
+	fi
+
+	create_public_packages_directories
+	create_symlink_mu-plugins
+	clear_themes_and_plugins_folder
+	install_private_plugins
+	install_private_themes
+	install_composer_packages
+	install_node_packages
+	build_webpack
+	download_and_install_languages_packages
+	shutdown_network
+
+	if is_image_build; then
+		build_docker_image
+	fi
+}
+
+# ARG_POSITIONAL_SINGLE([target],[dev or dist],[])
+# ARG_POSITIONAL_SINGLE([type],[filesystem or image],[])
+# ARG_HELP([Aztlan - A full cycle DevOps WordPress environment])
+# ARGBASH_GO()
+# needed because of Argbash --> m4_ignore([
+### START OF CODE GENERATED BY Argbash v2.9.0 one line above ###
+# Argbash is a bash code generator used to get arguments parsing right.
+# Argbash is FREE SOFTWARE, see https://argbash.io for more info
+# Generated online by https://argbash.io/generate
+
+die() {
+	local _ret="${2:-1}"
+	test "${_PRINT_HELP:-no}" = yes && print_help >&2
+	echo "$1" >&2
+	exit "${_ret}"
+}
+
+begins_with_short_option() {
+	local first_option all_short_options='h'
+	first_option="${1:0:1}"
+	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+}
+
+# THE DEFAULTS INITIALIZATION - POSITIONALS
+_positionals=()
+# THE DEFAULTS INITIALIZATION - OPTIONALS
+
+print_help() {
+	printf '%s\n' "Aztlan - A full cycle DevOps WordPress environment"
+	printf 'Usage: %s [-h|--help] <target> <type>\n' "$0"
+	printf '\t%s\n' "<target>: dev or dist"
+	printf '\t%s\n' "<type>: filesystem or image"
+	printf '\t%s\n' "-h, --help: Prints help"
+}
+
+parse_commandline() {
+	_positionals_count=0
+	while test $# -gt 0; do
+		_key="$1"
+		case "$_key" in
+		-h | --help)
+			print_help
+			exit 0
+			;;
+		-h*)
+			print_help
+			exit 0
+			;;
+		*)
+			_last_positional="$1"
+			_positionals+=("$_last_positional")
+			_positionals_count=$((_positionals_count + 1))
+			;;
+		esac
+		shift
+	done
+}
+
+handle_passed_args_count() {
+	local _required_args_string="'target' and 'type'"
+	test "${_positionals_count}" -ge 2 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 2 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+	test "${_positionals_count}" -le 2 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
+}
+
+assign_positional_args() {
+	local _positional_name _shift_for=$1
+	_positional_names="_arg_target _arg_type "
+
+	shift "$_shift_for"
+	for _positional_name in ${_positional_names}; do
+		test $# -gt 0 || break
+		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
+		shift
+	done
+}
+
+# OTHER STUFF GENERATED BY Argbash
+
+### END OF CODE GENERATED BY Argbash (sortof) ### ])
+
+dotenv_exists() {
+	[[ -f ".env" ]] && return 0 || return 1
+}
+
+is_image_build() {
+	[[ "${_arg_type}" == "image" ]]
+}
+
+is_filesystem_build() {
+	[[ "${_arg_type}" == "filesystem" ]]
+}
+
+is_dev_build() {
+	[[ "${_arg_target}" == "dev" ]]
+}
+
+is_dist_build() {
+	[[ "${_arg_target}" == "dist" ]]
+}
+
 docker_compose_run_with_host_user_bash() {
 	docker_compose_run_with_host_user wordpress-base bash -c "$@"
 }
